# Node.js with Angular
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'


    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure for Students(2bf0d891-91bb-4a64-a6a1-465c9cb1efbf)'
        appType: 'webApp'
        WebAppName: 'medappl'
        packageForLinux: 'dist/'